2021-06-23 14:40:45,501 INFO    MainThread:309 [wandb_setup.py:_flush():69] setting env: {}
2021-06-23 14:40:45,501 INFO    MainThread:309 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-23 14:40:45,501 INFO    MainThread:309 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '95f179e22100df8f8a6b067b3c508c849fe34da7'}
2021-06-23 14:40:45,501 INFO    MainThread:309 [wandb_init.py:_log_setup():337] Logging user logs to /home/aaneto/rna-work/wandb/run-20210623_144045-22xtu7v2/logs/debug.log
2021-06-23 14:40:45,501 INFO    MainThread:309 [wandb_init.py:_log_setup():338] Logging internal logs to /home/aaneto/rna-work/wandb/run-20210623_144045-22xtu7v2/logs/debug-internal.log
2021-06-23 14:40:45,502 INFO    MainThread:309 [wandb_init.py:init():370] calling init triggers
2021-06-23 14:40:45,502 INFO    MainThread:309 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-06-23 14:40:45,502 INFO    MainThread:309 [wandb_init.py:init():390] re-initializing run, found existing run on stack: 2tmiq4pa
2021-06-23 14:40:45,503 INFO    MainThread:309 [wandb_run.py:finish():1294] finishing run aaneto/gpt-3/2tmiq4pa
2021-06-23 14:40:45,504 INFO    MainThread:309 [jupyter.py:save_history():339] not saving jupyter history
2021-06-23 14:40:45,504 INFO    MainThread:309 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-06-23 14:40:45,504 INFO    MainThread:309 [wandb_init.py:_jupyter_teardown():269] cleaning up jupyter logic
2021-06-23 14:40:45,504 INFO    MainThread:309 [wandb_run.py:_atexit_cleanup():1594] got exitcode: 0
2021-06-23 14:40:45,504 INFO    MainThread:309 [wandb_run.py:_restore():1566] restore
2021-06-23 14:40:46,724 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 767
  total_bytes: 767
}

2021-06-23 14:40:47,300 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 767
  total_bytes: 5504
}

2021-06-23 14:40:47,402 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1154
  total_bytes: 5504
}

2021-06-23 14:40:47,504 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2253
  total_bytes: 5504
}

2021-06-23 14:40:47,606 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:47,708 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:47,810 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:47,911 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:48,013 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:48,114 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:48,216 INFO    MainThread:309 [wandb_run.py:_wait_for_finish():1716] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5504
  total_bytes: 5504
}

2021-06-23 14:40:49,691 INFO    MainThread:309 [wandb_run.py:_show_files():1938] logging synced files
2021-06-23 14:40:49,697 INFO    MainThread:309 [wandb_init.py:init():419] starting backend
2021-06-23 14:40:49,697 INFO    MainThread:309 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-23 14:40:49,700 INFO    MainThread:309 [backend.py:ensure_launched():135] starting backend process...
2021-06-23 14:40:49,715 INFO    MainThread:309 [backend.py:ensure_launched():139] started backend process with pid: 11140
2021-06-23 14:40:49,715 INFO    MainThread:309 [wandb_init.py:init():424] backend started and connected
2021-06-23 14:40:49,725 INFO    MainThread:309 [wandb_run.py:_label_probe_notebook():845] probe notebook
2021-06-23 14:40:49,726 INFO    MainThread:309 [wandb_init.py:init():472] updated telemetry
2021-06-23 14:40:49,726 INFO    MainThread:309 [wandb_init.py:init():491] communicating current version
2021-06-23 14:40:50,435 INFO    MainThread:309 [wandb_init.py:init():496] got version response 
2021-06-23 14:40:50,435 INFO    MainThread:309 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-06-23 14:40:50,908 INFO    MainThread:309 [wandb_init.py:init():529] starting run threads in backend
2021-06-23 14:40:51,881 INFO    MainThread:309 [wandb_run.py:_console_start():1624] atexit reg
2021-06-23 14:40:51,882 INFO    MainThread:309 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.WRAP
2021-06-23 14:40:51,882 INFO    MainThread:309 [wandb_run.py:_redirect():1535] Wrapping output streams.
2021-06-23 14:40:51,884 INFO    MainThread:309 [wandb_run.py:_redirect():1559] Redirects installed.
2021-06-23 14:40:51,884 INFO    MainThread:309 [wandb_init.py:init():554] run started, returning control to user process
2021-06-23 14:40:51,924 INFO    MainThread:309 [wandb_config.py:__setitem__():141] config set learning_rate = 0.0003 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f6a023ea3a0>>
2021-06-23 14:40:51,924 INFO    MainThread:309 [wandb_run.py:_config_callback():873] config_cb learning_rate 0.0003 None
